let en = {
    profile: "A technology enthusiast with skills based on webdevelopment, having worked with Laravel, Yii, Nest (and other Node frameworks), and even backends made in python (Flask). Im also confident using bootstrap, tailwind as frontend frameworks. I have knowledge in graphic design using open-source tools such as GIMP and Inkscape. I am familiar with GNU/Linux systems. Currently, I am studying Computer Science at UiP and have a technical degree in Information Technology from FAETERJ. I am passionate about personal projects and have already developed a wide variety of them. Portuguese is my native language, but additionally, I am fluent in English and currently studying Spanish.",
    experience: "Experiences in the Field",
    IrmaraTitle: "Irmara and Maringá Licenças (04/2018 - 07/2021)",
    IrmaraSubtitle: "As a Graphic Designer and Administrative Assistant",
    IrmaraText: "Before entering the technology field, I worked in two companies as an Administrative Assistant, where I had the opportunity to perform digital management and maintenance functions, as well as produce graphic materials such as flyers, business cards, and others. This experience provided me with a solid foundation in the corporate and bureaucratic world, as well as teaching me widely necessary management concepts for the development area.",
    social: "Social",
    skills: "Skills",
    education: "Education",
    faetec: "Information Technology - Faeterj, (2014-2016)",
    UoP: "Computer Science - UoP,  (2023-Present)",
    languages: "Languages",
    portuguese: "Native Portuguese",
    english: "Fluent English",
    spanish: "Learning Spanish",
    airTalentTitle:"Air Talent (07/2021 - 12/2022)",
    airTalentSubtitle:"Development Internship",
    airTalentText:"I completed a brief internship at Air Talent, where I had the opportunity to learn the fundamentals of web platform management. During this period, I had contact with technologies used internally in the company, such as React, WordPress, among others.",
    SpeedNowTitle:"SpeedNow (01/2022 - 09/2022)",
    SpeedNowSubtitle:"Computational Support Analyst",
    SpeedNowText:"At SpeedNow, I worked as a Systems Analyst, where I was able to improve my skills in developing EAD platforms, using technologies such as Laravel and CodeIgniter3. In addition, I participated in editing the standard graphical interface of our application for different users. I was responsible for participating in meetings with clients, aiming to adjust and optimize the development process according to each one's needs. I also worked with databases and local APIs, as well as communication between them and clients. This experience was fundamental to the development of my career, as I was able to acquire technical and practical knowledge, as well as improve my communication and teamwork skills.",
    paragonSoftwareTitle:"Paragon Software Solutions (10/2022 - 02/2023)",
    paragonSoftwareSubtitle:"Graphic Designer and Front-end Developer",
    paragonSoftwareText:"At Paragon Software Solutions, I was responsible for leading the development of the company's visual identity, including the design of the vector format logo and the creation of the website. In addition, I worked as a front-end developer, using technologies such as HTML, CSS, and JavaScript to create responsive and accessible interfaces. This experience allowed me to improve my skills in graphic design and web development, as well as develop a broader vision of the intersection between these areas.",
    transpanoramaTitle:"Transpanorama (04/2023 - Present)",
    transpanoramaSubtitle:"Developer and Designer",
    transpanoramaText:"During my tenure at Transpanorama, I significantly enhanced my skill set by actively participating in diverse projects and assuming leadership roles. I successfully led the development of multiple initiatives, which included building Laravel CRUD applications with Bootstrap frontends, implementing Python-based automations, and developing APIs to seamlessly integrate the company's database with third-party systems. Additionally, I contributed to the creation of business intelligence solutions, focusing on data visualization to provide valuable insights. Furthermore, I played a pivotal role in expanding existing systems deployed in various languages and frameworks, such as PHP, Vue, and React, thereby contributing to the company's growth and efficiency.",
    projects: "Personal Projects",
    links: "Social Links",
    linksTitle: "Aditional links",
    print: "Print this document",
    };

let pt = {
    profile: "Entusiasta de tecnologia com habilidades baseadas em desenvolvimento web, tendo trabalhado com Laravel, Yii, Nest (e outros frameworks Node), e até mesmo backends feitos em Python (Flask). Também tenho confiança em usar Bootstrap, Tailwind como frameworks frontend. Tenho conhecimento em design gráfico usando ferramentas de código aberto como GIMP e Inkscape. Estou familiarizado com sistemas GNU/Linux. Atualmente, estou estudando Ciência da Computação na UiP e tenho um diploma técnico em Tecnologia da Informação pela FAETERJ. Sou apaixonado por projetos pessoais e já desenvolvi uma grande variedade deles. O português é minha língua nativa, mas além disso, sou fluente em inglês e atualmente estou estudando espanhol.",
    experience: "Experiência no campo",
    IrmaraTitle: "Irmara e Maringá Licenças(04/2018 - 07/2021)",
    IrmaraSubtitle: "Como Designer Gráfico e Assistente Administrativo",
    IrmaraText: "Antes de ingressar no campo da tecnologia, trabalhei em duas empresas como Assistente Administrativo, onde tive a oportunidade de realizar funções de gerenciamento e manutenção digital, além de produzir materiais gráficos como panfletos, cartões de visita e outros. Essa experiência me proporcionou uma base sólida no mundo corporativo e burocrático, além de me ensinar conceitos de gerenciamento amplamente necessários para a área de desenvolvimento.",
    social: "Social",
    skills: "Habilidades",
    education: "Educação",
    faetec: "Tecnologia da Informação - Faeterj, (2014-2016)",
    UoP: "Ciência da Computação - UoP, (2023-Presente)",
    languages: "Idiomas",
    portuguese: "Português Nativo",
    english: "Inglês Fluente",
    spanish: "Estudando Espanhol",
    airTalentTitle: "Talento Aéreo (07/2021 - 12/2022)",
    airTalentText: "Completei um breve estágio no Talento Aéreo, onde tive a oportunidade de aprender os fundamentos do gerenciamento de plataforma web. Durante esse período, tive contato com tecnologias usadas internamente na empresa, como React, WordPress, entre outras.",
    SpeedNowTitle: "SpeedNow (01/2022 - 09/2022)",
    SpeedNowSubtitle: "Analista de Suporte Computacional",
    SpeedNowText: "Na SpeedNow, trabalhei como Analista de Sistemas, onde pude aprimorar minhas habilidades no desenvolvimento de plataformas EAD, usando tecnologias como Laravel e CodeIgniter3. Além disso, participei da edição da interface gráfica padrão de nossa aplicação para diferentes usuários. Fui responsável por participar de reuniões com clientes, visando ajustar e otimizar o processo de desenvolvimento de acordo com as necessidades de cada um. Também trabalhei com bancos de dados e APIs locais, bem como comunicação entre eles e os clientes. Essa experiência foi fundamental para o desenvolvimento da minha carreira, pois pude adquirir conhecimento técnico e prático, além de aprimorar minhas habilidades de comunicação e trabalho em equipe.",
    paragonSoftwareTitle: "Soluções de Software Paragon (10/2022 - 02/2023)",
    paragonSoftwareSubtitle: "Designer Gráfico e Desenvolvedor Front-end",
    paragonSoftwareText: "Na Paragon Software Solutions, fui responsável por liderar o desenvolvimento da identidade visual da empresa, incluindo o design do logotipo em formato vetorial e a criação do site. Além disso, trabalhei como desenvolvedor front-end, usando tecnologias como HTML, CSS e JavaScript para criar interfaces responsivas e acessíveis. Essa experiência me permitiu aprimorar minhas habilidades em design gráfico e desenvolvimento web, além de desenvolver uma visão mais ampla da interseção entre essas áreas.",
    transpanoramaTitle: "Transpanorama (04/2023 - Presente)",
    transpanoramaSubtitle: "Desenvolvedor e Designer",
    transpanoramaText: "Durante meu tempo na Transpanorama, aprimorei significativamente meu conjunto de habilidades ao participar ativamente de diversos projetos e assumir papéis de liderança. Liderei com sucesso o desenvolvimento de múltiplas iniciativas, que incluíram a construção de aplicativos Laravel CRUD com frontends Bootstrap, implementação de automações baseadas em Python e desenvolvimento de APIs para integrar perfeitamente o banco de dados da empresa com sistemas de terceiros. Além disso, contribuí para a criação de soluções de inteligência empresarial, focando na visualização de dados para fornecer insights valiosos. Além disso, desempenhei um papel fundamental na expansão de sistemas existentes implantados em várias linguagens e frameworks, como PHP, Vue e React, contribuindo assim para o crescimento e eficiência da empresa.",
    projects: "Projetos Pessoais",
    links: "Links Sociais",
    linksTitle: "Links Adicionais",
    print: "Imprimir este documento"
    }

